### ISSUE TITLE
Ottix.net domain

### ISSUE THREAD

**Issue by kmorin18** [ixmaps/ixnode#116]
Hello,

In the list of domains to be tested, there is the old Ottawa IX website (ottix.net)
The new domain is ogix.ca

Regards,

Karl

**Comment by Andrew-Clement** [comment]
Thanks,  

A.

On Sep 10, 2020, at 2:43 PM, kmorin18 <notifications@github.com> wrote:


Hello,

In the list of domains to be tested, there is the old Ottawa IX website (ottix.net)
The new domain is ogix.ca

Regards,

Karl

**Comment by colinmccann** [comment]
Updated, thanks
