### ISSUE TITLE
ixnode: not submitting data to the server

### ISSUE THREAD

**Issue by agamba** [ixmaps/ixnode#15]
After updating the latest version of ixnode I noticed that after completion of both raw socket and native traceroute command the application is not submitting the data to the server.

I believe this is happening since last updated on Jun 14, 2015

**Comment by agamba** [comment]
I will be checking whether this issues has to do with the move of the server to SSL (https://)

**Comment by vid** [comment]
Good idea. You can change the submit location here: https://github.com/ixmaps/ixnode/blob/master/lib/processor.js#L23

**Comment by agamba** [comment]
confirmed!
Ixnode is not submitting data! and it is not due to changes in SSL on ixmaps server
proof of no error due to SSL from client: TRid: 76400 (submitted from local server using ixnode json)

**Comment by agamba** [comment]
ok! issue resolved 
changing https://github.com/ixmaps/ixnode/blob/master/lib/processor.js#L23
to
var SUBMIT_URI = 'https://www.ixmaps.ca/application/controller/gather_tr.php';
fixed the problem.

ixnode is now submitting data. proof: TRid: 76408

P.S.
This makes me think we need to to think about loading ixnode's settings from the server, otherwise the client will have to re-install all ixnode just to upgrade a simple URI change

**Comment by vid** [comment]
Yes, if a stable endpoint can be set up on the server then it can retrieve settings from there. If you want to do this make a new issue and include the endpoint and data format.
