### ISSUE TITLE
Defining error messages convention for ixnode/client

### ISSUE THREAD

**Issue by agamba** [ixmaps/ixnode#16]
We need to agree on how to submit errors occurred when ixnode client is running.

In recent test I found this one:
"error": "{\"aborted\":true}"

I suggest the use of an array model in which each error item contains:
* origin: where it was produced
* description: as much info as we could get
* value: exact error message
* ++

Please add on ideas about how to submit error in the ixnode client and suggestions on how these will/may affect the analysis of the posted data.

**Comment by vid** [comment]
duplicate #3
