### ISSUE TITLE
IXmapsNode-launcher not working on OS X 10.10.3

### ISSUE THREAD

**Issue by dcwalk** [ixmaps/ixnode#29]
When attempting to open the IXmapsNode launcher the following message appears, re-downloading the .dmg package hasn't resolved the issue. I am running OS X 10.10.3.

![screen shot 2015-06-25 at 7 47 40 pm](https://cloud.githubusercontent.com/assets/4692834/8368401/bd960852-1b77-11e5-9186-30237fb385f3.png)

Error reads: "IXmapsNode-launcher.app” is damaged and can’t be opened. You should
move it to the Trash."

**Comment by dcwalk** [comment]
Upon review not sure if this is related to #20 ?

**Comment by vid** [comment]
This depends on #6 making the process more like a usual Mac application.
