### ISSUE TITLE
Running ixnode in OS X 10.10.3 without su leads to a non-recoverable and difficult to understand error

### ISSUE THREAD

**Issue by dcwalk** [ixmaps/ixnode#30]
When running the app (bypassing the launcher, just opening it from ixnode.app) an error that prevents and further progress arises after selecting a trset.

I am assuming this is an error that is expected based on previous notes in the README, however is there a way to make this more human-focused? Perhaps explain what the cause is, why it will not work or point to some further documentation?

Screenshot below...
![screen shot 2015-06-25 at 7 50 23 pm](https://cloud.githubusercontent.com/assets/4692834/8368603/59f5f746-1b7a-11e5-91db-caf7da07db1d.png)

**Comment by vid** [comment]
This depends on #6 making the process more like a usual Mac application.
