### ISSUE TITLE
After completing trset "Close" button difficult to click

### ISSUE THREAD

**Issue by dcwalk** [ixmaps/ixnode#31]
Encountered the issue whereby after the trset has competed and the progress bar disappears I am not able to select 'close.' Occasionally it seems that only a narrow border around the button is actually clickable but hovering over most of the button does not allow for any clicking. As a result I am stuck on this screen and it seems I have no choice but to quit the application in order to submit new routes or try anything else.

Running OS X 10.10.3 for reference, preview 2.0(.1) dmg. Because I've been so screenshot happy, please find another, of limited value:

![screen shot 2015-06-25 at 7 58 01 pm](https://cloud.githubusercontent.com/assets/4692834/8369760/937240e4-1b8c-11e5-85dc-019873cab770.png)

**Comment by vid** [comment]
It is difficult to select close, though possible through careful positioning. You can select it using the tab key. It needs to be resolved for the release version.
