### ISSUE TITLE
error: cannot resolve host causes the trset batch to stop

### ISSUE THREAD

**Issue by agamba** [ixmaps/ixnode#36]
"error: cannot resolve host "stfranciscollege.edu"", source: /Users/antonio/mywebapps/ixnode/src/js/frontend.js (36)
![screen shot 2015-06-29 at 2 30 01 pm](https://cloud.githubusercontent.com/assets/999407/8415243/661ead3a-1e6b-11e5-9fcd-a37876fc91d2.png)

**Comment by vid** [comment]
duplicate #11
