### ISSUE TITLE
TRgen2 testing hostname target TRset 

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/ixnode#42]
TRset of target hostnames for testing all possible conditions that TRgen2 needs to handle, This would be included in the TRset list and first round testers would be encouraged to run TRgen2 against it.

**Comment by vid** [comment]
test trset is now bundled with the app and available at https://github.com/ixmaps/ixnode/blob/master/testing.trset

**Comment by Andrew-Clement** [comment]
Good to see an iniital test trset, but only two hostnames to test against? What about hosts that may present a variety of different challenges, esp when tested from different locations - eg where the route doesn't complete, where there are likely to be complex routings (lots of load balancing) and other possible conditions??

**Comment by vid** [comment]
Please go to that page, click the edit button and add test conditions as appropriate.

**Comment by Andrew-Clement** [comment]
OK, but it appears that you didn't have a set of test conditions or target hosts in mind when developing and testing the code???


On 2015-07-12, at 2:32 PM, "David H. Mason" <notifications@github.com> wrote:

Please go to that page, click the edit button and add test conditions as appropriate.

**Comment by vid** [comment]
This new feature isn't related to ongoing development and testing of the code.

**Comment by Andrew-Clement** [comment]
Please clarify what you mean by 'this new feature'

**Comment by vid** [comment]
The new feature is what we're commenting on, creating a new trset for testing multiple conditions. The feature is implemented in the software, which will run against its general functionality. The trset needs to be populated with target hosts. When testing I use specific hosts that may not be particularly relevant to the project.

**Comment by Andrew-Clement** [comment]
I don't see this testing trset as a "new feature" to be implemented in software. It is fine for there to be a specific TRset customized for testing trgen, and explicitly labeled as such.  We can then direct users to it, and during the next testing phase have it at the top of the list so a kind of default.  It would also be relatively easy to add new hosts as we learn more about the rioting variations we need to handle.

How about including in the list the specific hosts you are already using for testing?



On 2015-07-12, at 7:24 PM, "David H. Mason" <notifications@github.com> wrote:

The new feature is what we're commenting on, creating a new trset for testing multiple conditions. The feature is implemented in the software, which will run against its general functionality. The trset needs to be populated with target hosts. When testing I use specific hosts that may not be particularly relevant to the project.

**Comment by vid** [comment]
This issue is about a requirement to add a testing trset and add it to the client trset list (it's at the bottom of the list), which is exactly what https://github.com/ixmaps/ixnode/commit/ca0ca11b7b9f2d922f51b317e71edc812b79f9d2 does. It is easy to add new hosts by editing the file outlined.

As part of a group, the suggestion is for people to add relevant testing hosts to the file.
