### ISSUE TITLE
TRgen2 - addtional itmes to capture 

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/ixnode#43]
IF THEY WOULD NOT SIGNIFICANTLY DELAY completion of the current version., it would be useful to capture the following items:
- Submitter ASN/ISP (Anto will add this to current submission)
- TRset name, from which this destination hostname is selected. or whether user specified.
- Computer model (if readily obtainable - used later for analysis of user cohort) 
- Browser version(if readily obtainable - used later for analysis of user cohort) 
- dest ASN/ISP (could be derived later from TR??)
- dest country, city (could be derived later from TR??)
- dest SSL (does the dest site enable SSL by default - only if readily obtainable) 

Some these would be good to report to the submitted as soon as possible soon after TR generation completion:
- Submitter ISP [ASN] 
- Submitter City
- dest ISP[ASN] (could be derived later from TR)
- dest country, city (could be derived later from TR)
- dest SSL (does the dest site enable SSL by default - only if readily obtainable) 
+
Countries (boomeranged?), carriers, suspected NSA interception cities en route

Some of these would also be good to have included in the TR summary in a revised TR Details screen:
- Submitter ASN/ISP
- TRset name, from which this destination hostname is selected. or whether user specified.
- dest ASN/ISP 
- dest country, city 
- country sequence (boomeranged?), carrier sequence (with stars), suspected US NSA cities passed through
- dest SSL (does the dest site enable SSL by default)

Any of these not easily implemented within the current version should be held over for discussion about including in the next revision.

**Comment by vid** [comment]
The user agent string can be picked up by the submission script on the server. It looks like this:

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36`

and allows determining the browser version and operating system, but it's not possible to include computer brand outside apple, windows, mac, etc.

ASN and IP can also be determined and added any time in the future so I suggest we focus solely on core client features, and consider those features post rollout, even adding them to another repo so we can keep client features focused and reducing.

**Comment by Andrew-Clement** [comment]
Good.

Yes, the client should be kept as stripped down as possible, so glad to hear these additional items can all be captured on the server.

On 2015-07-12, at 1:42 PM, "David H. Mason" <notifications@github.com> wrote:

The user agent string can be picked up by the submission script on the server. It looks like this:

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36

and allows determining the browser version and operating system, but it's not possible to include computer brand outside apple, windows, mac, etc.

ASN and IP can also be determined and added any time in the future so I suggest we focus solely on core client features, and consider those features post rollout, even adding them to another repo so we can keep client features focused and reducing.
