### ISSUE TITLE
ixnode test on osx 10.8: documentation

### ISSUE THREAD

**Issue by agamba** [ixmaps/ixnode#44]
$ git clone git@github.com:ixmaps/ixnode.git
Cloning into 'ixnode'...
Warning: Permanently added the RSA host key for IP address '----??---' to the list of known hosts.
remote: Counting objects: 653, done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 653 (delta 39), reused 0 (delta 0), pack-reused 567
Receiving objects: 100% (653/653), 164.27 KiB | 0 bytes/s, done.
Resolving deltas: 100% (360/360), done.
Checking connectivity... done.
antonios-MacBook-Pro-2:mywebapps antonio$ cd ixnode
antonios-MacBook-Pro-2:ixnode antonio$ npm install -g gulp && npm install && gulp build && npm run-script webpack-production
-bash: npm: command not found
antonios-MacBook-Pro-2:ixnode antonio$ . ~/.nvm/nvm.sh
antonios-MacBook-Pro-2:ixnode antonio$ nvm use iojs
Now using io.js v2.3.0 (npm v2.11.1)
antonios-MacBook-Pro-2:ixnode antonio$ npm install -g gulp && npm install && gulp build && npm run-script webpack-production
/Users/antonio/.nvm/versions/io.js/v2.3.0/bin/gulp -> /Users/antonio/.nvm/versions/io.js/v2.3.0/lib/node_modules/gulp/bin/gulp.js
gulp@3.9.0 /Users/antonio/.nvm/versions/io.js/v2.3.0/lib/node_modules/gulp
├── pretty-hrtime@1.0.0
├── interpret@0.6.4
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.1.1
├── tildify@1.1.0 (os-homedir@1.0.0)
├── v8flags@2.0.9 (user-home@1.1.1)
├── semver@4.3.6
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.1.0 (extend@2.0.1, rechoir@0.6.1, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, beeper@1.1.0, lodash._reescape@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.0, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)
npm WARN package.json ixnode@0.0.1 license should be a valid SPDX license expression
 
> raw-socket2@1.2.5 install /Users/antonio/Documents/mywebapps/ixnode/node_modules/raw-socket2
> node-gyp rebuild

  CXX(target) Release/obj.target/raw/src/raw.o
  SOLINK_MODULE(target) Release/raw.node
 
> fsevents@0.3.6 install /Users/antonio/Documents/mywebapps/ixnode/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> fsevents@0.3.6 install /Users/antonio/Documents/mywebapps/ixnode/node_modules/watchify/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> ws@0.5.0 install /Users/antonio/Documents/mywebapps/ixnode/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

> ws@0.4.31 install /Users/antonio/Documents/mywebapps/ixnode/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

> fsevents@0.3.6 install /Users/antonio/Documents/mywebapps/ixnode/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
open@0.0.5 node_modules/open

async@1.3.0 node_modules/async

http-proxy@1.11.1 node_modules/http-proxy
├── eventemitter3@1.1.1
└── requires-port@0.0.1

mkdirp@0.5.1 node_modules/mkdirp
└── minimist@0.0.8

vinyl-source-stream@1.1.0 node_modules/vinyl-source-stream
├── vinyl@0.4.6 (clone-stats@0.0.1, clone@0.2.0)
└── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)

gulp-util@3.0.6 node_modules/gulp-util
├── array-differ@1.0.0
├── array-uniq@1.0.2
├── lodash._reescape@3.0.0
├── lodash._reevaluate@3.0.0
├── beeper@1.1.0
├── lodash._reinterpolate@3.0.0
├── object-assign@3.0.0
├── replace-ext@0.0.1
├── minimist@1.1.1
├── vinyl@0.5.0 (clone-stats@0.0.1, clone@1.0.2)
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── lodash.template@3.6.2 (lodash._basetostring@3.0.1, lodash._basecopy@3.0.1, lodash._basevalues@3.0.0, lodash.templatesettings@3.1.0, lodash.restparam@3.6.1, lodash.escape@3.0.0, lodash._isiterateecall@3.0.9, lodash.keys@3.1.2)
├── through2@2.0.0 (xtend@4.0.0, readable-stream@2.0.1)
├── multipipe@0.1.2 (duplexer2@0.0.2)
└── dateformat@1.0.11 (get-stdin@4.0.1, meow@3.3.0)

react-hot-loader@1.2.7 node_modules/react-hot-loader
├── react-hot-api@0.4.4
└── source-map@0.1.40 (amdefine@0.1.1)

gulp-streamify@0.0.5 node_modules/gulp-streamify
├── plexer@0.0.2
├── readable-stream@1.1.13 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
└── gulp-util@2.2.20 (lodash._reinterpolate@2.4.1, minimist@0.2.0, multipipe@0.1.2, chalk@0.5.1, vinyl@0.2.3, lodash.template@2.4.1, through2@0.5.1, dateformat@1.0.11)

express@4.13.1 node_modules/express
├── escape-html@1.0.2
├── merge-descriptors@1.0.0
├── array-flatten@1.1.0
├── cookie@0.1.3
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── methods@1.1.1
├── fresh@0.3.0
├── range-parser@1.0.2
├── path-to-regexp@0.1.6
├── content-type@1.0.1
├── etag@1.7.0
├── vary@1.0.0
├── parseurl@1.3.0
├── content-disposition@0.5.0
├── serve-static@1.10.0
├── depd@1.0.1
├── qs@4.0.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.4.0 (unpipe@1.0.0)
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)
├── accepts@1.2.10 (negotiator@0.5.3, mime-types@2.1.2)
└── type-is@1.6.4 (media-typer@0.3.0, mime-types@2.1.2)

tape@4.0.0 node_modules/tape
├── inherits@2.0.1
├── defined@0.0.0
├── resumer@0.0.0
├── deep-equal@1.0.0
├── through@2.3.8
├── object-inspect@1.0.0
└── glob@5.0.13 (path-is-absolute@1.0.0, once@1.3.2, inflight@1.0.4, minimatch@2.0.8)

babel-loader@5.3.1 node_modules/babel-loader
├── object-assign@3.0.0
└── loader-utils@0.2.10 (big.js@3.1.3, json5@0.4.0)

request@2.58.0 node_modules/request
├── caseless@0.10.0
├── aws-sign2@0.5.0
├── forever-agent@0.6.1
├── stringstream@0.0.4
├── oauth-sign@0.8.0
├── tunnel-agent@0.4.1
├── isstream@0.1.2
├── extend@2.0.1
├── json-stringify-safe@5.0.1
├── node-uuid@1.4.3
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── qs@3.1.0
├── mime-types@2.0.14 (mime-db@1.12.0)
├── http-signature@0.11.0 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── bl@0.9.4 (readable-stream@1.0.33)
├── form-data@1.0.0-rc1 (mime-types@2.1.2)
├── tough-cookie@2.0.0
├── hawk@2.3.1 (cryptiles@2.0.4, sntp@1.0.9, boom@2.8.0, hoek@2.14.0)
└── har-validator@1.8.0 (commander@2.8.1, chalk@1.1.0, is-my-json-valid@2.12.0, bluebird@2.9.32)

cheerio@0.19.0 node_modules/cheerio
├── dom-serializer@0.1.0 (domelementtype@1.1.3)
├── entities@1.1.1
├── css-select@1.0.0 (boolbase@1.0.0, css-what@1.0.0, nth-check@1.0.1, domutils@1.4.3)
└── htmlparser2@3.8.3 (domelementtype@1.3.0, domutils@1.5.1, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13)

gulp@3.9.0 node_modules/gulp
├── pretty-hrtime@1.0.0
├── interpret@0.6.4
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.1.1
├── tildify@1.1.0 (os-homedir@1.0.0)
├── v8flags@2.0.9 (user-home@1.1.1)
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── semver@4.3.6
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.1.0 (extend@2.0.1, rechoir@0.6.1, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)

gulp-uglify@1.2.0 node_modules/gulp-uglify
├── deap@1.0.0
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
└── uglify-js@2.4.19 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.5.4, source-map@0.1.34)

webpack-dev-server@1.10.1 node_modules/webpack-dev-server
├── supports-color@1.3.1
├── connect-history-api-fallback@1.1.0
├── strip-ansi@2.0.1 (ansi-regex@1.1.1)
├── webpack-dev-middleware@1.2.0 (memory-fs@0.2.0, mime@1.3.4)
├── stream-cache@0.0.2
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
└── serve-index@1.7.1 (escape-html@1.0.2, parseurl@1.3.0, batch@0.5.2, http-errors@1.3.1, accepts@1.2.10, debug@2.2.0, mime-types@2.1.2)

bootstrap@3.3.5 node_modules/bootstrap

react-bootstrap@0.23.7 node_modules/react-bootstrap
└── classnames@2.1.3

lodash@3.10.0 node_modules/lodash

gulp-shell@0.4.2 node_modules/gulp-shell
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── async@1.2.1
└── lodash@3.9.3

gulp-notify@2.2.0 node_modules/gulp-notify
├── lodash.template@3.6.2 (lodash._basecopy@3.0.1, lodash._reinterpolate@3.0.0, lodash._basetostring@3.0.1, lodash._basevalues@3.0.0, lodash.templatesettings@3.1.0, lodash.restparam@3.6.1, lodash.escape@3.0.0, lodash._isiterateecall@3.0.9, lodash.keys@3.1.2)
├── node.extend@1.1.5 (is@3.0.1)
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
└── node-notifier@4.2.3 (shellwords@0.1.0, growly@1.2.0, minimist@1.1.1, which@1.1.1, semver@4.3.6, lodash.clonedeep@3.0.1, cli-usage@0.1.1)

node-libs-browser@0.5.2 node_modules/node-libs-browser
├── https-browserify@0.0.0
├── tty-browserify@0.0.0
├── constants-browserify@0.0.1
├── path-browserify@0.0.0
├── os-browserify@0.1.2
├── string_decoder@0.10.31
├── process@0.11.1
├── domain-browser@1.1.4
├── punycode@1.3.2
├── querystring-es3@0.2.1
├── assert@1.3.0
├── timers-browserify@1.4.1
├── stream-browserify@1.0.0 (inherits@2.0.1)
├── events@1.0.2
├── vm-browserify@0.0.4 (indexof@0.0.1)
├── console-browserify@1.1.0 (date-now@0.1.4)
├── util@0.10.3 (inherits@2.0.1)
├── http-browserify@1.7.0 (inherits@2.0.1, Base64@0.2.1)
├── readable-stream@1.1.13 (isarray@0.0.1, inherits@2.0.1, core-util-is@1.0.1)
├── url@0.10.3 (querystring@0.2.0)
├── buffer@3.3.1 (ieee754@1.1.6, is-array@1.0.1, base64-js@0.0.8)
├── browserify-zlib@0.1.4 (pako@0.2.7)
└── crypto-browserify@3.2.8 (ripemd160@0.2.0, pbkdf2-compat@2.0.1, sha.js@2.2.6)

raw-socket2@1.2.5 node_modules/raw-socket2
└── nan@1.8.4

react@0.13.3 node_modules/react
└── envify@3.4.0 (through@2.3.8, jstransform@10.1.0)

gulp-less@3.0.3 node_modules/gulp-less
├── object-assign@2.1.1
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
├── accord@0.15.2 (indx@0.2.3, convert-source-map@0.4.1, fobject@0.0.3, when@3.7.3, resolve@1.1.6, glob@4.5.3, uglify-js@2.4.23)
└── less@2.5.1 (graceful-fs@3.0.8, mime@1.3.4, image-size@0.3.5, source-map@0.4.3, errno@0.1.3, promise@6.1.0)

babel-core@5.6.15 node_modules/babel-core
├── slash@1.0.0
├── babel-plugin-remove-debugger@1.0.1
├── babel-plugin-inline-environment-variables@1.0.1
├── babel-plugin-eval@1.0.1
├── babel-plugin-remove-console@1.0.1
├── babel-plugin-react-constant-elements@1.0.3
├── babel-plugin-member-expression-literals@1.0.1
├── babel-plugin-property-literals@1.0.1
├── babel-plugin-jscript@1.0.1
├── babel-plugin-undefined-to-void@1.1.6
├── shebang-regex@1.0.0
├── trim-right@1.0.0
├── to-fast-properties@1.0.1
├── babel-plugin-react-display-name@1.0.3
├── path-exists@1.0.0
├── path-is-absolute@1.0.0
├── babel-plugin-constant-folding@1.0.1
├── fs-readdir-recursive@0.1.2
├── babel-plugin-proto-to-assign@1.0.3
├── babel-plugin-dead-code-elimination@1.0.2
├── strip-json-comments@1.0.2
├── babel-plugin-runtime@1.0.7
├── private@0.1.6
├── globals@6.4.1
├── estraverse@4.1.0
├── esutils@2.0.2
├── convert-source-map@1.1.1
├── babel-plugin-undeclared-variables-check@1.0.2 (leven@1.0.2)
├── home-or-tmp@1.0.0 (os-tmpdir@1.0.1, user-home@1.1.1)
├── line-numbers@0.2.0 (left-pad@0.0.3)
├── output-file-sync@1.1.1 (xtend@4.0.0)
├── js-tokens@1.0.1
├── debug@2.2.0 (ms@0.7.1)
├── detect-indent@3.0.1 (get-stdin@4.0.1, minimist@1.1.1)
├── chalk@1.1.0 (supports-color@2.0.0, escape-string-regexp@1.0.3, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── ast-types@0.7.8
├── repeating@1.1.3 (is-finite@1.0.1)
├── resolve@1.1.6
├── minimatch@2.0.8 (brace-expansion@1.1.0)
├── is-integer@1.0.4 (is-finite@1.0.1, is-nan@1.1.0)
├── source-map@0.4.3 (amdefine@0.1.1)
├── source-map-support@0.2.10 (source-map@0.1.32)
├── acorn-jsx@1.0.3 (acorn@1.2.2)
├── regexpu@1.2.0 (regjsgen@0.2.0, regenerate@1.2.1, regjsparser@0.1.4, recast@0.10.16)
├── regenerator@0.8.31 (through@2.3.8, esprima-fb@13001.1.0-dev-harmony-fb, commoner@0.10.3, recast@0.10.16, defs@1.1.0)
└── core-js@0.9.18

babel@5.6.14 node_modules/babel
├── slash@1.0.0
├── path-exists@1.0.0
├── fs-readdir-recursive@0.1.2
├── path-is-absolute@1.0.0
├── convert-source-map@1.1.1
├── output-file-sync@1.1.1 (xtend@4.0.0)
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── glob@5.0.13 (inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.8)
├── source-map@0.4.3 (amdefine@0.1.1)
└── chokidar@1.0.3 (arrify@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, is-binary-path@1.0.1, readdirp@1.3.0, anymatch@1.3.0, fsevents@0.3.6)

watchify@3.2.3 node_modules/watchify
├── defined@1.0.0
├── xtend@4.0.0
├── through2@0.6.5 (readable-stream@1.0.33)
├── outpipe@1.1.1 (shell-quote@1.4.3)
├── anymatch@1.3.0 (arrify@1.0.0, micromatch@2.1.6)
├── browserify@10.2.4 (https-browserify@0.0.0, htmlescape@1.1.0, tty-browserify@0.0.0, builtins@0.0.7, constants-browserify@0.0.1, path-browserify@0.0.0, isarray@0.0.1, os-browserify@0.1.2, inherits@2.0.1, commondir@0.0.1, string_decoder@0.10.31, through2@1.1.1, process@0.11.1, stream-browserify@1.0.0, has@1.0.0, shell-quote@0.0.1, punycode@1.3.2, domain-browser@1.1.4, duplexer2@0.0.2, querystring-es3@0.2.1, assert@1.3.0, timers-browserify@1.4.1, deps-sort@1.3.9, util@0.10.3, events@1.0.2, concat-stream@1.4.10, parents@1.0.1, vm-browserify@0.0.4, read-only-stream@1.1.1, console-browserify@1.1.0, subarg@1.0.0, http-browserify@1.7.0, readable-stream@1.1.13, url@0.10.3, shasum@1.0.1, buffer@3.3.1, labeled-stream-splicer@1.0.2, browser-resolve@1.9.0, resolve@1.1.6, glob@4.5.3, JSONStream@1.0.4, syntax-error@1.1.4, crypto-browserify@3.9.14, browser-pack@5.0.1, browserify-zlib@0.1.4, insert-module-globals@6.5.2, module-deps@3.8.1)
└── chokidar@1.0.3 (arrify@1.0.0, path-is-absolute@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, is-binary-path@1.0.1, readdirp@1.3.0, fsevents@0.3.6)

socket.io@1.3.5 node_modules/socket.io
├── debug@2.1.0 (ms@0.6.2)
├── has-binary-data@0.1.3 (isarray@0.0.1)
├── socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2, socket.io-parser@2.2.2)
├── socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2, benchmark@1.0.0, json3@3.2.6)
└── engine.io@1.5.1 (base64id@0.1.0, debug@1.0.3, engine.io-parser@1.2.1, ws@0.5.0)

socket.io-client@1.3.5 node_modules/socket.io-client
├── to-array@0.1.3
├── indexof@0.0.1
├── debug@0.7.4
├── object-component@0.0.3
├── component-bind@1.0.0
├── backo2@1.0.2
├── component-emitter@1.1.2
├── has-binary@0.1.6 (isarray@0.0.1)
├── parseuri@0.0.2 (better-assert@1.0.2)
├── socket.io-parser@2.2.4 (isarray@0.0.1, benchmark@1.0.0, json3@3.2.6)
└── engine.io-client@1.5.1 (component-inherit@0.0.3, xmlhttprequest@1.5.0, debug@1.0.4, parsejson@0.0.1, parseqs@0.0.2, parseuri@0.0.4, engine.io-parser@1.2.1, has-cors@1.0.3, ws@0.4.31)

webpack@1.10.1 node_modules/webpack
├── interpret@0.5.2
├── tapable@0.1.9
├── supports-color@1.3.1
├── clone@1.0.2
├── memory-fs@0.2.0
├── async@0.9.2
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── enhanced-resolve@0.8.6 (graceful-fs@3.0.8)
├── webpack-core@0.6.5 (source-list-map@0.1.5, source-map@0.4.3)
├── uglify-js@2.4.23 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.5.4, source-map@0.1.34)
├── esprima@1.2.5
└── watchpack@0.2.8 (graceful-fs@3.0.8, chokidar@1.0.3)
[23:36:55] Using gulpfile ~/Documents/mywebapps/ixnode/gulpfile.js
[23:36:55] Starting 'setup'...
[23:36:55] Starting 'less'...
[23:36:55] Finished 'less' after 15 ms
[23:36:55] Finished 'setup' after 39 ms
[23:36:55] Starting 'build'...
[23:36:55] Finished 'build' after 9.51 μs

> ixnode@0.0.1 webpack-production /Users/antonio/Documents/mywebapps/ixnode
> webpack -p --config production.config.js

Hash: 0d6ce7eae708e7a5a373
Version: webpack 1.10.1
Time: 44463ms
          Asset     Size  Chunks             Chunk Names
    frontend.js   476 kB       0  [emitted]  frontend
frontend.js.map  4.14 MB       0  [emitted]  frontend
 [177] ./lib/default-options.js 404 bytes {0} [built]
    + 390 hidden modules
antonios-MacBook-Pro-2:ixnode antonio$

**Comment by agamba** [comment]
Success on osx 10.8!! after compiling natively!


-----
details below
-----

$ sudo npm start
Password:

> ixnode@0.0.1 start /Users/antonio/Documents/mywebapps/ixnode
> node server.js



IXnode server started at http://127.0.0.1:2040
Development mode: false
Connection
trsets 21


---------

![screen shot 2015-07-08 at 12 09 02 am](https://cloud.githubusercontent.com/assets/999407/8562892/0baa702c-2506-11e5-96a9-eeb5a9c32fe5.png)


![screen shot 2015-07-08 at 12 11 56 am](https://cloud.githubusercontent.com/assets/999407/8562895/1448259e-2506-11e5-8d75-1024c8570a7d.png)

**Comment by vid** [comment]
Great. I think the problem is having it see those packages in the distribution.

**Comment by agamba** [comment]
Right! so do you suggest to set some environmental variables? we can add to the PATH when ixnode.app initializes, would this work?

**Comment by vid** [comment]
No, we just need to make sure it includes all the files and it should be fine. The bundle should be completely self contained. 

To encourage other people to participate, Github should be used for to the point issues, not discussion, so let's move this to email.

**Comment by vid** [comment]
I updated the distribution script so it should include the files properly.
