### ISSUE TITLE
Stop after current trace didn't work 

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/ixnode#54]
Crashed software. Had to close window
![pastedgraphic-4](https://cloud.githubusercontent.com/assets/12848029/10809150/0a34a9b6-7db1-11e5-9463-6744d42b4d51.png)
![pastedgraphic-5](https://cloud.githubusercontent.com/assets/12848029/10809151/0a388568-7db1-11e5-8961-d11cfa70e4b2.png)

From terminal:

SUBMITTRACE post {
  "timeout": 750,
  "queries": 4,
  "dest": "juilliard.edu",
  "dest_ip": "107.22.178.157",
  "submitter": "AndrewC",
  "postal_code": "M5S",
  "maxhops": 24,
  "os": "Darwin",
  "traceroute_submissions": [
    {
      "client": "ixjs 0.0.1",
      "protocol": "ICMP",
      "tr_data": [
        [
          {
            "pass": 1,
            "hop": 1,
            "ttl": 1,
            "ip": "192.168.0.1",
            "rtt": "1.14"
          },
          {
            "pass": 1,
            "hop": 2,
            "ttl": 2,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 1,
            "hop": 3,
            "ttl": 3,
            "ip": "64.59.162.189",
            "rtt": "20.17"
          },
          {
            "pass": 1,
            "hop": 4,
            "ttl": 4,
            "ip": "66.163.68.129",
            "rtt": "16.75"
          },
          {
            "pass": 1,
            "hop": 5,
            "ttl": 5,
            "ip": "66.163.72.69",
            "rtt": "35.70"
          },
          {
            "pass": 1,
            "hop": 6,
            "ttl": 6,
            "ip": "66.163.75.66",
            "rtt": "78.17"
          },
          {
            "pass": 1,
            "hop": 7,
            "ttl": 7,
            "ip": "66.163.65.114",
            "rtt": "85.06"
          },
          {
            "pass": 1,
            "hop": 8,
            "ttl": 8,
            "ip": "206.223.119.98",
            "rtt": "78.63"
          },
          {
            "pass": 1,
            "hop": 9,
            "ttl": 9,
            "ip": "178.236.3.98",
            "rtt": "110.83"
          },
          {
            "pass": 1,
            "hop": 10,
            "ttl": 10,
            "ip": "54.240.228.244",
            "rtt": "113.72"
          },
          {
            "pass": 1,
            "hop": 11,
            "ttl": 11,
            "ip": "54.240.229.189",
            "rtt": "112.42"
          },
          {
            "pass": 1,
            "hop": 12,
            "ttl": 12,
            "ip": "54.240.228.173",
            "rtt": "111.81"
          },
          {
            "pass": 1,
            "hop": 13,
            "ttl": 13,
            "ip": "54.239.109.96",
            "rtt": "143.71"
          },
          {
            "pass": 1,
            "hop": 14,
            "ttl": 14,
            "ip": "54.239.109.87",
            "rtt": "109.89"
          },
          {
            "pass": 1,
            "hop": 15,
            "ttl": 15,
            "ip": "54.239.109.52",
            "rtt": "113.59"
          },
          {
            "pass": 1,
            "hop": 16,
            "ttl": 16,
            "ip": "54.239.109.73",
            "rtt": "98.17"
          },
          {
            "pass": 1,
            "hop": 17,
            "ttl": 17,
            "ip": "72.21.222.139",
            "rtt": "98.23"
          },
          {
            "pass": 1,
            "hop": 18,
            "ttl": 18,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 1,
            "hop": 19,
            "ttl": 19,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 1,
            "hop": 20,
            "ttl": 20,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 1,
            "hop": 21,
            "ttl": 21,
            "ip": "216.182.224.15",
            "rtt": "98.44"
          },
          {
            "pass": 1,
            "hop": 22,
            "ttl": 22,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 1,
            "hop": 23,
            "ttl": 23,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 1,
            "hop": 24,
            "ttl": 24,
            "rtt": -1,
            "err": "timeout"
          }
        ],
        [
          {
            "pass": 2,
            "hop": 1,
            "ttl": 1,
            "ip": "192.168.0.1",
            "rtt": "3.16"
          },
          {
            "pass": 2,
            "hop": 2,
            "ttl": 2,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 2,
            "hop": 3,
            "ttl": 3,
            "ip": "64.59.162.189",
            "rtt": "19.34"
          },
          {
            "pass": 2,
            "hop": 4,
            "ttl": 4,
            "ip": "66.163.68.129",
            "rtt": "21.27"
          },
          {
            "pass": 2,
            "hop": 5,
            "ttl": 5,
            "ip": "66.163.72.69",
            "rtt": "28.92"
          },
          {
            "pass": 2,
            "hop": 6,
            "ttl": 6,
            "ip": "66.163.75.66",
            "rtt": "77.21"
          },
          {
            "pass": 2,
            "hop": 7,
            "ttl": 7,
            "ip": "66.163.65.114",
            "rtt": "77.36"
          },
          {
            "pass": 2,
            "hop": 8,
            "ttl": 8,
            "ip": "206.223.119.98",
            "rtt": "80.40"
          },
          {
            "pass": 2,
            "hop": 9,
            "ttl": 9,
            "ip": "178.236.3.98",
            "rtt": "111.06"
          },
          {
            "pass": 2,
            "hop": 10,
            "ttl": 10,
            "ip": "54.240.228.244",
            "rtt": "113.22"
          },
          {
            "pass": 2,
            "hop": 11,
            "ttl": 11,
            "ip": "54.240.229.189",
            "rtt": "110.97"
          },
          {
            "pass": 2,
            "hop": 12,
            "ttl": 12,
            "ip": "54.240.228.173",
            "rtt": "112.75"
          },
          {
            "pass": 2,
            "hop": 13,
            "ttl": 13,
            "ip": "54.239.109.96",
            "rtt": "116.91"
          },
          {
            "pass": 2,
            "hop": 14,
            "ttl": 14,
            "ip": "54.239.109.87",
            "rtt": "111.75"
          },
          {
            "pass": 2,
            "hop": 15,
            "ttl": 15,
            "ip": "54.239.109.52",
            "rtt": "116.73"
          },
          {
            "pass": 2,
            "hop": 16,
            "ttl": 16,
            "ip": "54.239.109.73",
            "rtt": "105.65"
          },
          {
            "pass": 2,
            "hop": 17,
            "ttl": 17,
            "ip": "72.21.222.139",
            "rtt": "96.63"
          },
          {
            "pass": 2,
            "hop": 18,
            "ttl": 18,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 2,
            "hop": 19,
            "ttl": 19,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 2,
            "hop": 20,
            "ttl": 20,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 2,
            "hop": 21,
            "ttl": 21,
            "ip": "216.182.224.15",
            "rtt": "113.76"
          },
          {
            "pass": 2,
            "hop": 22,
            "ttl": 22,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 2,
            "hop": 23,
            "ttl": 23,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 2,
            "hop": 24,
            "ttl": 24,
            "rtt": -1,
            "err": "timeout"
          }
        ],
        [
          {
            "pass": 3,
            "hop": 1,
            "ttl": 1,
            "rtt": -1,
            "err": "timeout"
          }
        ],
        [
          {
            "pass": 4,
            "hop": 1,
            "ttl": 1,
            "rtt": -1,
            "err": "timeout"
          }
        ]
      ]
    }
  ]
}
STATUS: Stopping after current host
passed 1024
STATUS: Stopping after current host
STATUS: Stopping after current host
passed 1090
passed 1592
passed 2092
passed 2594
passed 3096
exiting due to no client response
logout

[Process completed]

**Comment by vid** [comment]
Would need details to reproduce this.
