### ISSUE TITLE
Avoid opening a Terminal window?

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/ixnode#57]
Why need to open a terminal window each time? Likely confusing to some who are not familiar with it. Can this be avoided, or at least be closed immediately automatically?

**Comment by vid** [comment]
this depends on how the software is bundled for each platform. it's kind of a feature since it lets the user close the app more intentionally and see debug message.s

**Comment by Andrew-Clement** [comment]
A feature for the more savvy, potentially confusing for those who are not familiar with Terminal. Not a priority at this time.
