### ISSUE TITLE
error running "sudo npm start" on Ubuntu

### ISSUE THREAD

**Issue by agamba** [ixmaps/ixnode#65]
I think this is a dumb question but any ideas why I can run 
"npm start" (which fails due to not being root)
but "sudo npm start" tells me "sudo: npm: command not found"

---------------------------
anto@anto-ubuntu:~/mywebapps/IXmapsClient$ npm start

> IXmapsClient@0.0.1 start /home/anto/mywebapps/IXmapsClient
> node server.js

IXmapsClient server started at http://127.0.0.1:2040
Development mode: false
anto@anto-ubuntu:~/mywebapps/IXmapsClient$

**Comment by vid** [comment]
it really depends how you have your environment set up.
try `sudo bash` then `npm start` from there.

**Comment by agamba** [comment]
sudo bash did the trick, thanks.
need to re-sourced . ~/.nvm/nvm.sh then it works

**Comment by agamba** [comment]
Full terminal log.

anto@anto-ubuntu:~/mywebapps/IXmapsClient$ sudo bash
root@anto-ubuntu:~/mywebapps/IXmapsClient# . ~/.nvm/nvm.sh
root@anto-ubuntu:~/mywebapps/IXmapsClient# nvm use node 5.2.0
Now using node v5.2.0 (npm v3.3.12)
root@anto-ubuntu:~/mywebapps/IXmapsClient# npm start

> IXmapsClient@0.0.1 start /home/anto/mywebapps/IXmapsClient
> node server.js



IXmapsClient server started at http://127.0.0.1:2040
Development mode: false
Connection
sending prefs { submitter: 'lodeanto.ubuntu.prerelease',
  city: '',
  postal_code: 'M5V',
  isp: 'Colombia' }
sending geoip { ip_address: '201.245.56.136',
  city: '',
  region: null,
  country: 'CO',
  postal_code: null,
  asn: '19429',
  isp: 'Colombia',
  lat: 4.5981,
  lon: -74.0758 }
trsets 26
info: {"submitter":"lodeanto.ubuntu.prerelease","postal_code":"M5V","dest":"","trset":"30: sites in the Toronto area","queries":4,"timeout":750,"maxhops":24,"raw_protocol":"ICMP","max_sequential_errors":4,"include_platform_traceroute":false,"platform_protocol":"Default","platform_limit_ms":60000,"city":"","isp":"Colombia"}
info: TRSET ["www.utoronto.ca","ocad.ca","ryerson.ca","yorku.ca","georgebrown.ca","humber.ca","centennialcollege.ca","cbstraining.com","wycliffecollege.ca","rom.on.ca","ago.net","hhof.com","gardinermuseum.com","ontariosciencecentre.ca","casmuseum.org","thedrakehotel.ca","miagallery.ca","godardgallery.com","tso.ca","national.ballet.ca","coc.ca","torontozoo.com","tocentre.com","fortyork.ca","mocca.ca","stlawrencemarket.com","cntower.ca","theex.com","theaircanadacentre.com","rogerscentre.com","torontoeatoncentre.com","fairviewmall.ca","yorkdale.com","atriumonbay.com","bayviewvillageshops.com","thestar.com","torontosun.com","eyeweekly.com","nowtoronto.com","edge.ca","q107.com","chumfm.com","chfi.com","sonycentre.ca","mirvish.com","stlc.com","ricohcoliseum.com","masseyhall.com","leespalace.com","rivoli.ca","cestwhat.com","sneaky-dees.com","themodclub.com","elmocambo.ca","horseshoetavern.com","theguvernment.com","secondcity.com"]
STATUS: Host www.utoronto.ca
info: now running www.utoronto.ca from 30: sites in the Toronto area
info: options{
  "submitter": "lodeanto.ubuntu.prerelease",
  "postal_code": "M5V",
  "dest": "www.utoronto.ca",
  "trset": "30: sites in the Toronto area",
  "queries": 4,
  "timeout": 750,
  "maxhops": 24,
  "raw_protocol": "ICMP",
  "max_sequential_errors": 4,
  "include_platform_traceroute": false,
  "platform_protocol": "Default",
  "platform_limit_ms": 60000,
  "city": "",
  "isp": "Colombia"
}
hop: {"pass":1,"hop":1,"ttl":1,"ip":"192.168.1.1","rtt":"6.92"}
hop: {"pass":1,"hop":2,"ttl":2,"ip":"192.168.0.1","rtt":"10.59"}
hop: {"pass":1,"hop":3,"ttl":3,"rtt":-1,"err":"timeout"}
hop: {"pass":1,"hop":4,"ttl":4,"ip":"10.6.0.157","rtt":"85.33"}
hop: {"pass":1,"hop":5,"ttl":5,"ip":"10.5.4.74","rtt":"84.01"}
hop: {"pass":1,"hop":6,"ttl":6,"ip":"62.115.58.157","rtt":"117.99"}
hop: {"pass":1,"hop":7,"ttl":7,"ip":"62.115.12.22","rtt":"114.62"}
hop: {"pass":1,"hop":8,"ttl":8,"rtt":-1,"err":"timeout"}
hop: {"pass":1,"hop":9,"ttl":9,"rtt":-1,"err":"timeout"}
hop: {"pass":1,"hop":10,"ttl":10,"rtt":-1,"err":"timeout"}
hop: {"pass":1,"hop":11,"ttl":11,"ip":"54.230.80.41","rtt":"123.81"}
complete pass 1
pass: 0
hop: {"pass":2,"hop":1,"ttl":1,"ip":"192.168.1.1","rtt":"4.75"}
hop: {"pass":2,"hop":2,"ttl":2,"ip":"192.168.0.1","rtt":"7.02"}
hop: {"pass":2,"hop":3,"ttl":3,"rtt":-1,"err":"timeout"}
hop: {"pass":2,"hop":4,"ttl":4,"ip":"10.6.0.157","rtt":"88.65"}
hop: {"pass":2,"hop":5,"ttl":5,"ip":"201.244.1.5","rtt":"80.17"}
hop: {"pass":2,"hop":6,"ttl":6,"ip":"62.115.58.157","rtt":"141.70"}
hop: {"pass":2,"hop":7,"ttl":7,"ip":"62.115.12.22","rtt":"142.09"}
hop: {"pass":2,"hop":8,"ttl":8,"rtt":-1,"err":"timeout"}
hop: {"pass":2,"hop":9,"ttl":9,"rtt":-1,"err":"timeout"}
hop: {"pass":2,"hop":10,"ttl":10,"rtt":-1,"err":"timeout"}
hop: {"pass":2,"hop":11,"ttl":11,"ip":"54.230.80.41","rtt":"197.99"}
complete pass 2
pass: 1
hop: {"pass":3,"hop":1,"ttl":1,"ip":"192.168.1.1","rtt":"5.18"}
hop: {"pass":3,"hop":2,"ttl":2,"ip":"192.168.0.1","rtt":"12.63"}
hop: {"pass":3,"hop":3,"ttl":3,"rtt":-1,"err":"timeout"}
hop: {"pass":3,"hop":4,"ttl":4,"ip":"10.6.0.157","rtt":"182.00"}
hop: {"pass":3,"hop":5,"ttl":5,"ip":"201.244.1.5","rtt":"118.05"}
hop: {"pass":3,"hop":6,"ttl":6,"ip":"62.115.58.157","rtt":"181.44"}
hop: {"pass":3,"hop":7,"ttl":7,"ip":"62.115.12.22","rtt":"163.13"}
hop: {"pass":3,"hop":8,"ttl":8,"rtt":-1,"err":"timeout"}
hop: {"pass":3,"hop":9,"ttl":9,"rtt":-1,"err":"timeout"}
hop: {"pass":3,"hop":10,"ttl":10,"rtt":-1,"err":"timeout"}
hop: {"pass":3,"hop":11,"ttl":11,"ip":"54.230.80.41","rtt":"189.19"}
complete pass 3
pass: 2
hop: {"pass":4,"hop":1,"ttl":1,"ip":"192.168.1.1","rtt":"2.55"}
hop: {"pass":4,"hop":2,"ttl":2,"ip":"192.168.0.1","rtt":"2.14"}
hop: {"pass":4,"hop":3,"ttl":3,"rtt":-1,"err":"timeout"}
hop: {"pass":4,"hop":4,"ttl":4,"ip":"10.6.0.157","rtt":"160.10"}
hop: {"pass":4,"hop":5,"ttl":5,"ip":"10.5.4.74","rtt":"191.15"}
hop: {"pass":4,"hop":6,"ttl":6,"ip":"62.115.58.157","rtt":"203.46"}
hop: {"pass":4,"hop":7,"ttl":7,"ip":"62.115.12.22","rtt":"225.52"}
hop: {"pass":4,"hop":8,"ttl":8,"rtt":-1,"err":"timeout"}
hop: {"pass":4,"hop":9,"ttl":9,"rtt":-1,"err":"timeout"}
hop: {"pass":4,"hop":10,"ttl":10,"rtt":-1,"err":"timeout"}
hop: {"pass":4,"hop":11,"ttl":11,"ip":"54.230.80.41","rtt":"146.59"}
complete pass 4
pass: 3
done: 4 queries
SUBMITTRACE post {
  "timeout": 750,
  "queries": 4,
  "dest": "www.utoronto.ca",
  "dest_ip": "54.230.80.41",
  "submitter": "lodeanto.ubuntu.prerelease",
  "postal_code": "M5V",
  "maxhops": 24,
  "os": "Linux",
  "traceroute_submissions": [
    {
      "client": "IXmapsClient prerelease",
      "protocol": "ICMP",
      "tr_data": [
        [
          {
            "pass": 1,
            "hop": 1,
            "ttl": 1,
            "ip": "192.168.1.1",
            "rtt": "6.92"
          },
          {
            "pass": 1,
            "hop": 2,
            "ttl": 2,
            "ip": "192.168.0.1",
            "rtt": "10.59"
          },
          {
            "pass": 1,
            "hop": 3,
            "ttl": 3,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 1,
            "hop": 4,
            "ttl": 4,
            "ip": "10.6.0.157",
            "rtt": "85.33"
          },
          {
            "pass": 1,
            "hop": 5,
            "ttl": 5,
            "ip": "10.5.4.74",
            "rtt": "84.01"
          },
          {
            "pass": 1,
            "hop": 6,
            "ttl": 6,
            "ip": "62.115.58.157",
            "rtt": "117.99"
          },
          {
            "pass": 1,
            "hop": 7,
            "ttl": 7,
            "ip": "62.115.12.22",
            "rtt": "114.62"
          },
          {
            "pass": 1,
            "hop": 8,
            "ttl": 8,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 1,
            "hop": 9,
            "ttl": 9,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 1,
            "hop": 10,
            "ttl": 10,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 1,
            "hop": 11,
            "ttl": 11,
            "ip": "54.230.80.41",
            "rtt": "123.81"
          }
        ],
        [
          {
            "pass": 2,
            "hop": 1,
            "ttl": 1,
            "ip": "192.168.1.1",
            "rtt": "4.75"
          },
          {
            "pass": 2,
            "hop": 2,
            "ttl": 2,
            "ip": "192.168.0.1",
            "rtt": "7.02"
          },
          {
            "pass": 2,
            "hop": 3,
            "ttl": 3,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 2,
            "hop": 4,
            "ttl": 4,
            "ip": "10.6.0.157",
            "rtt": "88.65"
          },
          {
            "pass": 2,
            "hop": 5,
            "ttl": 5,
            "ip": "201.244.1.5",
            "rtt": "80.17"
          },
          {
            "pass": 2,
            "hop": 6,
            "ttl": 6,
            "ip": "62.115.58.157",
            "rtt": "141.70"
          },
          {
            "pass": 2,
            "hop": 7,
            "ttl": 7,
            "ip": "62.115.12.22",
            "rtt": "142.09"
          },
          {
            "pass": 2,
            "hop": 8,
            "ttl": 8,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 2,
            "hop": 9,
            "ttl": 9,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 2,
            "hop": 10,
            "ttl": 10,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 2,
            "hop": 11,
            "ttl": 11,
            "ip": "54.230.80.41",
            "rtt": "197.99"
          }
        ],
        [
          {
            "pass": 3,
            "hop": 1,
            "ttl": 1,
            "ip": "192.168.1.1",
            "rtt": "5.18"
          },
          {
            "pass": 3,
            "hop": 2,
            "ttl": 2,
            "ip": "192.168.0.1",
            "rtt": "12.63"
          },
          {
            "pass": 3,
            "hop": 3,
            "ttl": 3,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 3,
            "hop": 4,
            "ttl": 4,
            "ip": "10.6.0.157",
            "rtt": "182.00"
          },
          {
            "pass": 3,
            "hop": 5,
            "ttl": 5,
            "ip": "201.244.1.5",
            "rtt": "118.05"
          },
          {
            "pass": 3,
            "hop": 6,
            "ttl": 6,
            "ip": "62.115.58.157",
            "rtt": "181.44"
          },
          {
            "pass": 3,
            "hop": 7,
            "ttl": 7,
            "ip": "62.115.12.22",
            "rtt": "163.13"
          },
          {
            "pass": 3,
            "hop": 8,
            "ttl": 8,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 3,
            "hop": 9,
            "ttl": 9,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 3,
            "hop": 10,
            "ttl": 10,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 3,
            "hop": 11,
            "ttl": 11,
            "ip": "54.230.80.41",
            "rtt": "189.19"
          }
        ],
        [
          {
            "pass": 4,
            "hop": 1,
            "ttl": 1,
            "ip": "192.168.1.1",
            "rtt": "2.55"
          },
          {
            "pass": 4,
            "hop": 2,
            "ttl": 2,
            "ip": "192.168.0.1",
            "rtt": "2.14"
          },
          {
            "pass": 4,
            "hop": 3,
            "ttl": 3,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 4,
            "hop": 4,
            "ttl": 4,
            "ip": "10.6.0.157",
            "rtt": "160.10"
          },
          {
            "pass": 4,
            "hop": 5,
            "ttl": 5,
            "ip": "10.5.4.74",
            "rtt": "191.15"
          },
          {
            "pass": 4,
            "hop": 6,
            "ttl": 6,
            "ip": "62.115.58.157",
            "rtt": "203.46"
          },
          {
            "pass": 4,
            "hop": 7,
            "ttl": 7,
            "ip": "62.115.12.22",
            "rtt": "225.52"
          },
          {
            "pass": 4,
            "hop": 8,
            "ttl": 8,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 4,
            "hop": 9,
            "ttl": 9,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 4,
            "hop": 10,
            "ttl": 10,
            "rtt": -1,
            "err": "timeout"
          },
          {
            "pass": 4,
            "hop": 11,
            "ttl": 11,
            "ip": "54.230.80.41",
            "rtt": "146.59"
          }
        ]
      ],
      "result": "completed"
    }
  ]
}
saveTrContribution: Query failed: incorrect parametersERROR:  value too long for type character varying(25)
error: submission error {}
passed 1122
passed 1624
passed 2126
passed 2627
passed 3129
exiting due to no client response
root@anto-ubuntu:~/mywebapps/IXmapsClient#

**Comment by vid** [comment]
I'm not sure how the output you pasted relates, but it's pretty obviously a server side PostgreSQL problem.

**Comment by agamba** [comment]
Ok. got it. 
it has to do with submitter using more than 25 characters. we might one to restrict this on the client.
