### ISSUE TITLE
some issues with make_distributions.sh on prerelease brach (Mac OS X)

### ISSUE THREAD

**Issue by agamba** [ixmaps/ixnode#66]
I'm trying to upgrade the IXmapsClient package (dmg file) with the latest version (ixnode/prerelease)

Compilation goes ok, and also executing "sudo npm start" from my git cloned directory, works okay.

I then run ./make_distributions.sh and the files are created in dist/ixmaps-darwin 
Then I copy and replace the the files from dist/ixmaps-darwin to "/Applications/IXmapsClient.app/Contents/Resources/ixmaps-darwin"

When trying to run:
$ sudo ./start.sh 
or
sudo ./start.sh

I get the following error, any ideas? 
NOTE: is there a change that the script make_distributions.sh is not copying some of the required files?

Thank you

---------
$ sudo ./start.sh 

IXmapsClient local server

This minimal server requires root access to initiate low-level socket traces. We invite you to inspect the code for safety.

A browser window for your regular user should appear. If the browser window doesn't open, please go to http://localhost:2040

If you don't see the message IXmapsClient server started something has gone wrong. Please consult the http://www.ixmaps.ca web site.

./start.sh: line 14: cd: ./../Resources/ixmaps-darwin: No such file or directory
UID 0 DIR . USER root
module.js:339
    throw err;
          ^
Error: Cannot find module 'merge-descriptors'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Applications/IXmapsClient.app/Contents/Resources/ixmaps-darwin/node_modules/express/lib/express.js:16:13)
    at Module._compile (module.js:431:26)
    at Object.Module._extensions..js (module.js:449:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

**Comment by vid** [comment]
I'm afraid I don't know all the details involved in setting up for Mac. It does work for Linux so hopefully you can use it as a starting point.

**Comment by agamba** [comment]
I've figured out that in oder for the make_distributions.sh script to work successful on mac os (as well as linux), you need to build the app with nodejs 4.2. The errors reported here stating to occur when I used higher versions of nodejs, 5.0 ++, to compile the application.
