### ISSUE TITLE
Unknown issues when submitting traceroute data to server

### ISSUE THREAD

**Issue by agamba** [ixmaps/ixnode#67]
I just compiled the latest code on "prerelease" branch. 

"npm start" works ok. and app loads in browser. BUT at the moment of submitting data I get this error:
error: submission error {}

Any ideas what is going on? It seems that this is happening only with "prerelease" branch?

@vid, can you provide a copy of your local version working ok on ubuntu, or further insight on these?

thx

@anto

root@anto-ubuntu:~/mywebapps/IXmapsClient# npm start
...
           "pass": 4,
            "hop": 16,
            "ttl": 16,
            "ip": "142.103.59.207",
            "rtt": "73.76"
          }
        ]
      ],
      "result": "completed"
    }
  ]
}
error: submission error {}
...

**Comment by agamba** [comment]
Forgot to add this pic on the browser ubuntu/firefox

<img width="698" alt="screen shot 2015-12-06 at 9 50 54 pm" src="https://cloud.githubusercontent.com/assets/999407/11618154/1b2dcad6-9c65-11e5-9d4f-8de69c3afda0.png">

**Comment by vid** [comment]
I just tried it. Works fine. 

You can see the relevant lines here: 

https://github.com/ixmaps/ixnode/blob/master/lib/processor.js#L133

that would seem to indicate the response is mal formed JSON.

try displaying `res.body` before the error.

**Comment by agamba** [comment]
Thx @div, wrong JSON seems to be the cause. I've added new tr analysis code and it seems to be braking is some cases. 

Would res.body show me the full response from the sever?

thx again

**Comment by agamba** [comment]
ups. @vid

**Comment by vid** [comment]
Yes, res.body should show the full response. Note if there is a json.message it will be displayed in the running output.

**Comment by agamba** [comment]
@vid 
will try changes at
https://github.com/ixmaps/ixnode/blob/master/lib/processor.js#L133
and report

**Comment by agamba** [comment]
Using node 5.2.0. compilled successfully. trace runs ok, then getting error when attempting submission.
As indicated, I added the a few lines at https://github.com/ixmaps/ixnode/blob/master/lib/processor.js#L133
to debug (res.body)
See screen for the details. 
(@vid can you provide a working package, over here still not working when run as sudo ./node server.js)

<img width="1155" alt="screen shot 2015-12-14 at 12 04 42 am" src="https://cloud.githubusercontent.com/assets/999407/11773402/47673532-a1f7-11e5-9183-8bb6a5fcb626.png">

**Comment by vid** [comment]
You should stick to node 4.2, it's the long term stable release. 

This is the same issue as #65, it's a server side error.

**Comment by agamba** [comment]
ok, fixed
