### ISSUE TITLE
TRset  13: Civil_liberties_and...  stops after only the first host aclu.org.

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/ixnode#68]
Hi,

I ran this new trset, 13: Civil_liberties_and_privacy_advocacy_organizations_in_US and Canada  and it stopped after only the first host aclu.org. See below. 

Colin indicates it isn't a glitch in the .trset file between 
host        aclu.org
and
comment                CCR - Center for Constitutional Rights
host        ccrjustice.org

Any quick fixes would be appreciated, as this is a trset requested for the Little Sister (is watching you, too)  exhibition opening  tomorrow/today (Dec 10) at the Pratt Manhattan Gallery, in which IXmaps is one 9 artworks and activist projects that look back at the apparatus of government agencies and systems of control. https://www.pratt.edu/events/exhibitions/pratt-manhattan-gallery/ 

Thanks,

Andrew.

Output

Detailed output
49
completed
21:40:42
TR Set 13: civil liberties and privacy advocacy organizations in US and Canada completed. 1 of 13 successfully contributed.
48
info
21:40:42
done 13: civil liberties and privacy advocacy organizations in US and Canada
47
submitted
21:40:42
aclu.org
104.156.85.74
89178
Traceroute data saved successfully. 7 Hops were found.
46
done
21:40:40
aclu.org
104.156.85.74
4 queries
45
pass
21:40:40
aclu.org
104.156.85.74
3
44
hop
21:40:40
aclu.org
104.156.85.74
pass:4, hop:9, ttl:9, ip:104.156.85.74, rtt:66.30
43
hop
21:40:40
aclu.org
104.156.85.74
pass:4, hop:8, ttl:8, ip:206.81.81.71, rtt:74.92
42
hop
21:40:40
aclu.org
104.156.85.74
pass:4, hop:7, ttl:7, ip:66.163.74.158, rtt:70.40
41
hop
21:40:40
aclu.org
104.156.85.74
pass:4, hop:6, ttl:6, ip:66.163.74.82, rtt:59.51
40
hop
21:40:40
aclu.org
104.156.85.74
pass:4, hop:5, ttl:5, ip:66.163.68.129, rtt:59.97
39
hop
21:40:40
aclu.org
104.156.85.74
pass:4, hop:4, ttl:4, ip:66.163.72.9, rtt:57.02
38
hop
21:40:40
aclu.org
104.156.85.74
pass:4, hop:3, ttl:3, ip:64.59.162.185, rtt:24.17
37
hop
21:40:40
aclu.org
104.156.85.74
pass:4, hop:2, ttl:2, ip:0.0.0.0, rtt:8.56
36
hop
21:40:40
aclu.org
104.156.85.74
pass:4, hop:1, ttl:1, ip:192.168.0.1, rtt:3.50
35
pass
21:40:40
aclu.org
104.156.85.74
2
34
hop
21:40:40
aclu.org
104.156.85.74
pass:3, hop:9, ttl:9, ip:104.156.85.74, rtt:70.28
33
hop
21:40:40
aclu.org
104.156.85.74
pass:3, hop:8, ttl:8, ip:206.81.81.71, rtt:77.93
32
hop
21:40:39
aclu.org
104.156.85.74
pass:3, hop:7, ttl:7, ip:66.163.74.158, rtt:72.47
31
hop
21:40:39
aclu.org
104.156.85.74
pass:3, hop:6, ttl:6, ip:66.163.74.82, rtt:65.20
30
hop
21:40:39
aclu.org
104.156.85.74
pass:3, hop:5, ttl:5, ip:66.163.68.129, rtt:60.98
29
hop
21:40:39
aclu.org
104.156.85.74
pass:3, hop:4, ttl:4, ip:66.163.72.9, rtt:57.40
28
hop
21:40:39
aclu.org
104.156.85.74
pass:3, hop:3, ttl:3, ip:64.59.162.185, rtt:13.02
27
hop
21:40:39
aclu.org
104.156.85.74
pass:3, hop:2, ttl:2, ip:0.0.0.0, rtt:9.89
26
hop
21:40:39
aclu.org
104.156.85.74
pass:3, hop:1, ttl:1, ip:192.168.0.1, rtt:1.73
25
pass
21:40:39
aclu.org
104.156.85.74
1
24
hop
21:40:39
aclu.org
104.156.85.74
pass:2, hop:9, ttl:9, ip:104.156.85.74, rtt:61.31
23
hop
21:40:39
aclu.org
104.156.85.74
pass:2, hop:8, ttl:8, ip:206.81.81.71, rtt:82.49
22
hop
21:40:39
aclu.org
104.156.85.74
pass:2, hop:7, ttl:7, ip:66.163.74.158, rtt:68.13
21
hop
21:40:39
aclu.org
104.156.85.74
pass:2, hop:6, ttl:6, ip:66.163.74.82, rtt:70.36
20
hop
21:40:39
aclu.org
104.156.85.74
pass:2, hop:5, ttl:5, ip:66.163.68.129, rtt:62.98
19
hop
21:40:39
aclu.org
104.156.85.74
pass:2, hop:4, ttl:4, ip:66.163.72.9, rtt:65.71
18
hop
21:40:39
aclu.org
104.156.85.74
pass:2, hop:3, ttl:3, ip:64.59.162.185, rtt:14.99
17
hop
21:40:39
aclu.org
104.156.85.74
pass:2, hop:2, ttl:2, ip:0.0.0.0, rtt:13.36
16
hop
21:40:39
aclu.org
104.156.85.74
pass:2, hop:1, ttl:1, ip:192.168.0.1, rtt:2.80
15
pass
21:40:39
aclu.org
104.156.85.74
14
hop
21:40:39
aclu.org
104.156.85.74
pass:1, hop:9, ttl:9, ip:104.156.85.74, rtt:67.40
13
hop
21:40:39
aclu.org
104.156.85.74
pass:1, hop:8, ttl:8, ip:206.81.81.71, rtt:63.29
12
hop
21:40:39
aclu.org
104.156.85.74
pass:1, hop:7, ttl:7, ip:66.163.74.158, rtt:74.99
11
hop
21:40:38
aclu.org
104.156.85.74
pass:1, hop:6, ttl:6, ip:66.163.74.82, rtt:60.93
10
hop
21:40:38
aclu.org
104.156.85.74
pass:1, hop:5, ttl:5, ip:66.163.68.129, rtt:61.39
9
hop
21:40:38
aclu.org
104.156.85.74
pass:1, hop:4, ttl:4, ip:66.163.72.9, rtt:60.58
8
hop
21:40:38
aclu.org
104.156.85.74
pass:1, hop:3, ttl:3, ip:64.59.162.185, rtt:15.26
7
hop
21:40:38
aclu.org
104.156.85.74
pass:1, hop:2, ttl:2, ip:0.0.0.0, rtt:9.20
6
hop
21:40:38
aclu.org
104.156.85.74
pass:1, hop:1, ttl:1, ip:192.168.0.1, rtt:2.26
5
info
21:40:38
aclu.org
options submitter: AndrewC, postal_code: V8L, dest: aclu.org, trset: 13: civil liberties and privacy advocacy organizations in US and Canada, queries: 4, timeout: 750, maxhops: 24, raw_protocol: ICMP, max_sequential_errors: 4, include_platform_traceroute: false, platform_protocol: Default, platform_limit_ms: 60000, city: Sidney, isp: Shaw Communications Inc.
4
info
21:40:38
now running aclu.org from 13: civil liberties and privacy advocacy organizations in US and Canada
3
host
21:40:38
Host aclu.org
2
info
21:40:38
TRSET [aclu.org, , cdt.org, democraticmedia.org, eff.org, epic.org, privacyrights.org, bccla.org, ccla.org, fipa.bc.ca, iclmg.ca, liguedesdroits.ca, openmedia.org]
1
info
21:40:37
submitter:AndrewC, postal_code:V8L, dest:, trset:13: civil liberties and privacy advocacy organizations in US and Canada, queries:4, timeout:750, maxhops:24, raw_protocol:ICMP, max_sequential_errors:4, include_platform_traceroute:false, platform_protocol:Default, platform_limit_ms:60000, city:Sidney, isp:Shaw Communications Inc.

**Comment by vid** [comment]
The second host, ccrjustice.org, has two spaces after `host`. removing the second space should fix it.
 
```
host  ccrjustice.org
```

https://www.ixmaps.ca/trsets/13:_civil_liberties_and_privacy_advocacy_organizations_in_US_and_Canada.trset

**Comment by Andrew-Clement** [comment]
Thanks for your quick response David and spotting this subtle anomaly.

@Colin, could you correct and re-run the TRset, and then alert the Pratt folks. 

I'm surprised the software is so sensitive to this nuance. Isn't it standard that any extra spaces between syntactic elements are removed as part of the parsing, especially in such a simple situation as this. Also, it would be good to have an error message associated with failure to parse, to alert the user something has gone and what broke? 

I hope this can be fixed the next time the software is revised. In the meantime, we'll check the trsets more carefully.

**Comment by vid** [comment]
There are many things that can go wrong with parsing, that can yield many different results. It's best to use a more precise format than arbitrary text. However if using a text format consistency is key.

**Comment by Andrew-Clement** [comment]
OK. Not a priority at this point.
